extends:
  - stylelint-config-recommended
  - stylelint-prettier/recommended
plugins:
  - stylelint-order
ignoreFiles:
  - out/**/*
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - extends
        - tailwind
  order/properties-alphabetical-order: true
