name: main ブランチに push した際の CI/CD 処理
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: ビルドとデプロイ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '20.x'
    steps:
      - name: `main` ブランチをチェックアウトします
        uses: actions/checkout@v4
      - name: Node.js `v${{ matrix.node-version }}` を使用します
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm を準備します
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        env:
          CI: true
          GITHUB_PAGES: true
      - name: ビルド結果を GitHub Pages へ配置します。
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
